baseurl = "/"
languageCode = "en-us"
title = "currencystack.io"
Subtitle = "Your site's subtitle/tagline"
GithubID = "currencystack"
TwitterID = "getcurrencystack"
AnalyticsID = "Your Google Analytics tracking code"
DisqusShortname = "Your Disqus shortname"
Summary = true  # takes true or false
Content = true  # takes true or false
FooterMsg = "by PushBots Inc 2018"
theme = "hugo-theme-slim"
addThis = "ra-5c184c7e824cfa0a"