baseurl = "/"
languageCode = "en-us"
title = "currencystack.io"
Subtitle = "Your site's subtitle/tagline"
GithubID = "currencystack"
twitter = "getcurrencystack"
AnalyticsID = "UA-51748123-5"
DisqusShortname = "Your Disqus shortname"
Summary = true  # takes true or false
Content = true  # takes true or false
FooterMsg = "by PushBots Inc 2018"
theme = "hugo-theme-slim"
[params]
fullurl="https://blog.currencystack.io"
[social]
  github           = "currencystackio"
  twitter = "currencystackio"